/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DevlogRouteImport } from './routes/devlog'
import { Route as DesignRouteImport } from './routes/design'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorialIdRouteImport } from './routes/tutorial.$id'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DevlogRoute = DevlogRouteImport.update({
  id: '/devlog',
  path: '/devlog',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialIdRoute = TutorialIdRouteImport.update({
  id: '/tutorial/$id',
  path: '/tutorial/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/devlog': typeof DevlogRoute
  '/profile': typeof ProfileRoute
  '/tutorial/$id': typeof TutorialIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/devlog': typeof DevlogRoute
  '/profile': typeof ProfileRoute
  '/tutorial/$id': typeof TutorialIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/devlog': typeof DevlogRoute
  '/profile': typeof ProfileRoute
  '/tutorial/$id': typeof TutorialIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/design'
    | '/devlog'
    | '/profile'
    | '/tutorial/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/design' | '/devlog' | '/profile' | '/tutorial/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/design'
    | '/devlog'
    | '/profile'
    | '/tutorial/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DesignRoute: typeof DesignRoute
  DevlogRoute: typeof DevlogRoute
  ProfileRoute: typeof ProfileRoute
  TutorialIdRoute: typeof TutorialIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devlog': {
      id: '/devlog'
      path: '/devlog'
      fullPath: '/devlog'
      preLoaderRoute: typeof DevlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial/$id': {
      id: '/tutorial/$id'
      path: '/tutorial/$id'
      fullPath: '/tutorial/$id'
      preLoaderRoute: typeof TutorialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DesignRoute: DesignRoute,
  DevlogRoute: DevlogRoute,
  ProfileRoute: ProfileRoute,
  TutorialIdRoute: TutorialIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
